/* Auto-generated by build-data.py — edit project-meta.json, not this file. */
window.PORTFOLIO = {
  "owner": {
    "name": "Eduardo Carranza",
    "role": "Senior Graphic Designer",
    "tagline": "Senior graphic designer: identity, packaging and large-format work that ships.",
    "years": 13,
    "email": "eddiecarranza66@gmail.com",
    "phone": "(530) 405-7647",
    "location": "Palermo, CA",
    "linkedin": "https://www.linkedin.com/in/eduardo-carranza-7960743b/",
    "languages": [
      "English",
      "Spanish"
    ],
    "employers": [
      "PreZero",
      "Roplast",
      "Revolve Recycling"
    ]
  },
  "projects": [
    {
      "id": "identity",
      "name": "Brand Identity",
      "blurb": "Logos, marks and the guideline documents that keep them intact — the work that has to stay recognisable at any size, on any substrate, years after handover."
    },
    {
      "id": "prezero",
      "name": "PreZero",
      "blurb": "In-house at PreZero — sustainability at industrial scale, from facility photography to 80-inch trade-show banners."
    },
    {
      "id": "grubbets",
      "name": "Grubbets",
      "blurb": "Insect-based fertilizer, packaging and conference collateral for a circular-agriculture startup."
    },
    {
      "id": "roplast",
      "name": "Roplast & Revolve",
      "blurb": "In-house at Roplast and Revolve Recycling — trade-show environments, closed-loop recycling campaigns and event collateral."
    },
    {
      "id": "bags",
      "name": "Packaging Concepts",
      "blurb": "Carry-out and tamper-evident bag systems drawn in-house at Roplast, from unbranded stock ranges through to named programmes for grocery retail."
    },
    {
      "id": "early",
      "name": "Early Work",
      "blurb": "Student and first-job pieces, kept as an honest record of where the type exploration started."
    }
  ],
  "items": [
    {
      "slug": "puravida-logo",
      "source": "PuraVida_Logo.jpg",
      "srcW": 1122,
      "srcH": 653,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "puravida-logo-thumb.webp",
          "w": 480,
          "h": 279,
          "kb": 14.2
        },
        "card": {
          "webp": "puravida-logo-card.webp",
          "w": 900,
          "h": 524,
          "kb": 27.0
        },
        "full": {
          "webp": "puravida-logo-full.webp",
          "w": 1122,
          "h": 653,
          "kb": 35.1,
          "jpg": "puravida-logo-full.jpg",
          "jpgKb": 69.5
        }
      },
      "lqip": "puravida-logo-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAwb/xAAhEAABBAICAgMAAAAAAAAAAAACAAEDBAUREyESUTFBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAGREAAwADAAAAAAAAAAAAAAAAAAERMUFh/9oADAMBAAIRAxEAPwB/LZxxI6wC7F8bSVPPnRbjlFy2tMxjHim5xk2Tv9qXNWObTkbdfiLpTSt0djTy0FoR78Xf2hRcJSeUtGfQ+kITk//Z",
      "project": "identity",
      "title": "Pura Vida",
      "client": "Pura Vida",
      "year": "2018",
      "medium": "Logo",
      "featured": true,
      "blurb": "A compact wordmark for a brand whose name does most of the persuading.",
      "engagement": "Client project",
      "inhouse": false
    },
    {
      "slug": "revolve-branding-revolverecyclinglogo",
      "source": "Revolve Branding/RevolveRecyclingLogo.jpg",
      "srcW": 3200,
      "srcH": 2560,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "revolve-branding-revolverecyclinglogo-thumb.webp",
          "w": 480,
          "h": 384,
          "kb": 14.0
        },
        "card": {
          "webp": "revolve-branding-revolverecyclinglogo-card.webp",
          "w": 900,
          "h": 720,
          "kb": 28.9
        },
        "full": {
          "webp": "revolve-branding-revolverecyclinglogo-full.webp",
          "w": 2000,
          "h": 1600,
          "kb": 70.5,
          "jpg": "revolve-branding-revolverecyclinglogo-full.jpg",
          "jpgKb": 144.5
        }
      },
      "lqip": "revolve-branding-revolverecyclinglogo-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAATABgDASIAAhEBAxEB/8QAGgABAQACAwAAAAAAAAAAAAAAAAUBAgMEBv/EAB8QAAICAgIDAQAAAAAAAAAAAAECAAMEEQUTEiExUv/EABYBAQEBAAAAAAAAAAAAAAAAAAEAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAABEUH/2gAMAwEAAhEDEQA/APX32ddZYSFbzTV3hVIYb9y1l2BKjtdgyAePr7e4A+zvUGbvF/FyBkVB9aMTh49l0VAIiJjuMAfo3NfBfyIiRZVVX4AIiJJ//9k=",
      "project": "identity",
      "title": "Revolve Recycling Logo",
      "client": "Revolve Recycling",
      "year": "2019",
      "medium": "Identity · full brand guideline",
      "featured": false,
      "blurb": "The recycling mark and closed-loop system, delivered with a printed guideline covering the two Pantone colours and the type system.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "early-work-vaperatechlogofinal",
      "source": "Early Work/VapeRaTechLogoFinal.jpg",
      "srcW": 800,
      "srcH": 600,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "early-work-vaperatechlogofinal-thumb.webp",
          "w": 480,
          "h": 360,
          "kb": 3.9
        },
        "card": {
          "webp": "early-work-vaperatechlogofinal-card.webp",
          "w": 800,
          "h": 600,
          "kb": 6.6
        },
        "full": {
          "webp": "early-work-vaperatechlogofinal-full.webp",
          "w": 800,
          "h": 600,
          "kb": 6.6,
          "jpg": "early-work-vaperatechlogofinal-full.jpg",
          "jpgKb": 15.5
        }
      },
      "lqip": "early-work-vaperatechlogofinal-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAASABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAMBBv/EAB0QAAICAgMBAAAAAAAAAAAAAAABAhEDEgQhMUH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABgRAQADAQAAAAAAAAAAAAAAAAABESFh/9oADAMBAAIRAxEAPwDsrMcor1mSx7O7JZeNvGtmSeLFXq9p/QTx4tEu2wVFQAAAAH//2Q==",
      "project": "identity",
      "title": "VapeRaTech",
      "client": "VapeRaTech",
      "year": "Early",
      "medium": "Logo",
      "featured": false,
      "blurb": "An early tech mark, kept here as a reminder of where the type exploration started.",
      "engagement": "Client project",
      "inhouse": false
    },
    {
      "slug": "organicsposter-english-printready-48x36",
      "source": "OrganicsPoster_English_PrintReady_48x36.jpg",
      "srcW": 14784,
      "srcH": 11088,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "organicsposter-english-printready-48x36-thumb.webp",
          "w": 480,
          "h": 360,
          "kb": 24.5
        },
        "card": {
          "webp": "organicsposter-english-printready-48x36-card.webp",
          "w": 900,
          "h": 675,
          "kb": 66.5
        },
        "full": {
          "webp": "organicsposter-english-printready-48x36-full.webp",
          "w": 2000,
          "h": 1500,
          "kb": 216.2,
          "jpg": "organicsposter-english-printready-48x36-full.jpg",
          "jpgKb": 338.2
        }
      },
      "lqip": "organicsposter-english-printready-48x36-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAASABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAQFAv/EAB0QAAICAgMBAAAAAAAAAAAAAAABAgMEEQUSEyH/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQIE/8QAGREBAQADAQAAAAAAAAAAAAAAAAECETFB/9oADAMBAAIRAxEAPwDEx8f2sUUzRfFVxai5vbJMO5U2dm0XPkVYpdml8+EXe+s+MnrPzMZY1jinsHN9vq99tgucRUwAGAAAT//Z",
      "project": "prezero",
      "title": "The Organics Way",
      "client": "PreZero",
      "year": "2024",
      "medium": "48×36 in poster · print-ready",
      "featured": true,
      "blurb": "A four-foot-wide values poster that pairs six short claims with a photo mosaic inside a rounded lime frame — sized so each callout stays legible from across a convention hall.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "prezero-bsf-booth-backdrop",
      "source": "PreZero_BSF Booth Backdrop.png",
      "srcW": 1659,
      "srcH": 1283,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "prezero-bsf-booth-backdrop-thumb.webp",
          "w": 480,
          "h": 371,
          "kb": 36.2
        },
        "card": {
          "webp": "prezero-bsf-booth-backdrop-card.webp",
          "w": 900,
          "h": 696,
          "kb": 103.7
        },
        "full": {
          "webp": "prezero-bsf-booth-backdrop-full.webp",
          "w": 1659,
          "h": 1283,
          "kb": 295.1,
          "jpg": "prezero-bsf-booth-backdrop-full.jpg",
          "jpgKb": 414.3
        }
      },
      "lqip": "prezero-bsf-booth-backdrop-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAATABgDASIAAhEBAxEB/8QAGQABAQADAQAAAAAAAAAAAAAAAAQBAgUD/8QAIxAAAgIBAwMFAAAAAAAAAAAAAQIAAxEEBRMSFTEhMkFRUv/EABYBAQEBAAAAAAAAAAAAAAAAAAEAAv/EABoRAQACAwEAAAAAAAAAAAAAAAABEQISUSH/2gAMAwEAAhEDEQA/AKdTvlzWZq9FlOh3Z8dVzZz8SKimkVDkOZ7E1IBwr1GGyjH10+6quWPiJy7GJQG0BV+olc8NR1XxJ+RNlRR4UREy2xYit7lBiIiH/9k=",
      "project": "prezero",
      "title": "BSF Booth Backdrop",
      "client": "PreZero",
      "year": "2023",
      "medium": "Fabric booth graphic · 13×10 ft",
      "featured": true,
      "blurb": "An aerial photograph of the Jurupa Valley facility with the buildings traced in lime, turning an anonymous industrial campus into a specific, ownable place.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "2022-09-09-grubbetsfrass-retractablebanner-24x80",
      "source": "2022-09-09_GrubbetsFrass_RetractableBanner_24x80.jpg",
      "srcW": 7200,
      "srcH": 24000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "2022-09-09-grubbetsfrass-retractablebanner-24x80-thumb.webp",
          "w": 144,
          "h": 480,
          "kb": 11.4
        },
        "card": {
          "webp": "2022-09-09-grubbetsfrass-retractablebanner-24x80-card.webp",
          "w": 270,
          "h": 900,
          "kb": 30.1
        },
        "full": {
          "webp": "2022-09-09-grubbetsfrass-retractablebanner-24x80-full.webp",
          "w": 600,
          "h": 2000,
          "kb": 85.9,
          "jpg": "2022-09-09-grubbetsfrass-retractablebanner-24x80-full.jpg",
          "jpgKb": 135.6
        }
      },
      "lqip": "2022-09-09-grubbetsfrass-retractablebanner-24x80-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYAAcDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQG/8QAHRAAAgICAwEAAAAAAAAAAAAAAAECAxESBAUWIf/EABYBAQEBAAAAAAAAAAAAAAAAAAQCA//EABoRAAICAwAAAAAAAAAAAAAAAAABAhIRE1L/2gAMAwEAAhEDEQA/ANMuXW7HFzTYI11s93LP0B9k+Sck/pqEs6sAC6oyuz//2Q==",
      "project": "prezero",
      "title": "PreZero Frass Retractable Banner",
      "client": "PreZero",
      "year": "2022",
      "medium": "Large-format print · 24×80 in",
      "featured": true,
      "blurb": "An 80-inch-tall vertical banner built for trade-show floors, walking a visitor from the product photo down to five benefit claims without a single paragraph of body copy.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "recircle-ontario-california",
      "source": "RECIRCLE_Ontario_California.webp",
      "srcW": 1280,
      "srcH": 664,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "recircle-ontario-california-thumb.webp",
          "w": 480,
          "h": 249,
          "kb": 32.7
        },
        "card": {
          "webp": "recircle-ontario-california-card.webp",
          "w": 900,
          "h": 467,
          "kb": 88.5
        },
        "full": {
          "webp": "recircle-ontario-california-full.webp",
          "w": 1280,
          "h": 664,
          "kb": 155.3,
          "jpg": "recircle-ontario-california-full.jpg",
          "jpgKb": 200.0
        }
      },
      "lqip": "recircle-ontario-california-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEBf/EAB8QAAICAQQDAAAAAAAAAAAAAAECAAMRBBIhMSJBUf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAECESH/2gAMAwEAAhEDEQA/AHNrra5B5MRsMo3YYe4P44I7ImQt9i7wGPcFLBStZTfVUuoyDhfkJFbYxQsTzCUVBa6f/9k=",
      "project": "prezero",
      "title": "Sorting Line, Ontario",
      "client": "RECircle Solutions",
      "year": "2024",
      "medium": "Photography · food recovery, diversion facility",
      "featured": false,
      "blurb": "Pre-consumer food waste arrives here at the point it would otherwise be prepared for landfill. Instead it is diverted and put to its highest possible use in line with the food recovery hierarchy — photographed on the line where that decision gets made, crate by crate.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "grubbets-conference-handouts-2024-01-29-food-waste-craigk",
      "source": "Grubbets Conference Handouts/2024-01-29_Food Waste_CraigK.jpg",
      "srcW": 2625,
      "srcH": 3375,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "grubbets-conference-handouts-2024-01-29-food-waste-craigk-thumb.webp",
          "w": 373,
          "h": 480,
          "kb": 34.6
        },
        "card": {
          "webp": "grubbets-conference-handouts-2024-01-29-food-waste-craigk-card.webp",
          "w": 700,
          "h": 900,
          "kb": 82.9
        },
        "full": {
          "webp": "grubbets-conference-handouts-2024-01-29-food-waste-craigk-full.webp",
          "w": 1556,
          "h": 2000,
          "kb": 219.5,
          "jpg": "grubbets-conference-handouts-2024-01-29-food-waste-craigk-full.jpg",
          "jpgKb": 377.6
        }
      },
      "lqip": "grubbets-conference-handouts-2024-01-29-food-waste-craigk-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABMDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAUDBAL/xAAiEAACAQMEAgMAAAAAAAAAAAABAgADBCEFERIiBhQxQVH/xAAXAQEBAQEAAAAAAAAAAAAAAAACAQME/8QAFxEBAQEBAAAAAAAAAAAAAAAAABEBIf/aAAwDAQACEQMRAD8A0reO2zqfXq9h9Sa+li3YgtkStpxc3AIbA+ZN1avyvnCviTsc+9TWo9jE8s7cjmIgmus37ZNNuO85RUDElzuf2IhxozZ13MREUSP/2Q==",
      "project": "grubbets",
      "title": "Food Waste",
      "client": "Grubbets",
      "year": "2024",
      "medium": "Conference handout · large format",
      "featured": true,
      "blurb": "A full-page editorial spread on diverting food waste from landfill, built on a strong typographic hierarchy that carries a dense argument.",
      "engagement": "Client project",
      "inhouse": false
    },
    {
      "slug": "grubbets-frass-label-2022-04-14-grubbets-frass-f-b",
      "source": "Grubbets Frass Label/2022-04-14_Grubbets-Frass_F&B.jpeg",
      "srcW": 1182,
      "srcH": 811,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "grubbets-frass-label-2022-04-14-grubbets-frass-f-b-thumb.webp",
          "w": 480,
          "h": 329,
          "kb": 14.7
        },
        "card": {
          "webp": "grubbets-frass-label-2022-04-14-grubbets-frass-f-b-card.webp",
          "w": 900,
          "h": 618,
          "kb": 40.1
        },
        "full": {
          "webp": "grubbets-frass-label-2022-04-14-grubbets-frass-f-b-full.webp",
          "w": 1182,
          "h": 811,
          "kb": 60.8,
          "jpg": "grubbets-frass-label-2022-04-14-grubbets-frass-f-b-full.jpg",
          "jpgKb": 109.1
        }
      },
      "lqip": "grubbets-frass-label-2022-04-14-grubbets-frass-f-b-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAECAwQG/8QAHhAAAQQCAwEAAAAAAAAAAAAAAgABAwQFEhEhIjH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABgRAQADAQAAAAAAAAAAAAAAAAABESFh/9oADAMBAAIRAxEAPwDp55SGR2YuFnsWDCsRbdsqclUtSzbQvwyQ0rBUnjk7J1MtPGWjnm9EhQxuOmr2Ni+ISjgxda//2Q==",
      "project": "grubbets",
      "title": "Frass Label — Front & Back",
      "client": "Grubbets",
      "year": "2022",
      "medium": "Packaging label · 2 lb pouch",
      "featured": true,
      "blurb": "Front and back of a kraft pouch for an organic multi-purpose fertilizer, pairing hand-drawn farm line art with a compliance-dense back panel — both readable in the same glance.",
      "engagement": "Client project",
      "inhouse": false
    },
    {
      "slug": "grubbets-conference-handouts-2022-06-03-sustainable-aquaculture-01",
      "source": "Grubbets Conference Handouts/2022-06-03_Sustainable Aquaculture-01.jpg",
      "srcW": 1275,
      "srcH": 1650,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "grubbets-conference-handouts-2022-06-03-sustainable-aquaculture-01-thumb.webp",
          "w": 371,
          "h": 480,
          "kb": 27.0
        },
        "card": {
          "webp": "grubbets-conference-handouts-2022-06-03-sustainable-aquaculture-01-card.webp",
          "w": 695,
          "h": 900,
          "kb": 71.3
        },
        "full": {
          "webp": "grubbets-conference-handouts-2022-06-03-sustainable-aquaculture-01-full.webp",
          "w": 1275,
          "h": 1650,
          "kb": 173.5,
          "jpg": "grubbets-conference-handouts-2022-06-03-sustainable-aquaculture-01-full.jpg",
          "jpgKb": 262.8
        }
      },
      "lqip": "grubbets-conference-handouts-2022-06-03-sustainable-aquaculture-01-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABMDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAEEBQP/xAAhEAACAgEEAgMAAAAAAAAAAAAAAQIDEQQFBhIUIRUxUv/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAHBEAAgICAwAAAAAAAAAAAAAAAAECURIUAxET/9oADAMBAAIRAxEAPwC49gqU+iyS+O0/ak0zX8mtSz2Rw1NrnJOE8ILkVk2olBcaray5A0YXYisz9gekbHUaMWW5adtYZEtzoePYBDXgSyY+Uo/QAGvAZM//2Q==",
      "project": "grubbets",
      "title": "Sustainable Aquaculture",
      "client": "Grubbets",
      "year": "2022",
      "medium": "Conference handout · 8.5×11 in",
      "featured": false,
      "blurb": "A conference handout on reusing insect byproducts in fish farming, designed to be read once in a hallway and remembered after.",
      "engagement": "Client project",
      "inhouse": false
    },
    {
      "slug": "grubbets-conference-handouts-2022-06-03-sustainable-pet-food-01",
      "source": "Grubbets Conference Handouts/2022-06-03_Sustainable Pet Food-01.jpg",
      "srcW": 1275,
      "srcH": 1650,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "grubbets-conference-handouts-2022-06-03-sustainable-pet-food-01-thumb.webp",
          "w": 371,
          "h": 480,
          "kb": 24.9
        },
        "card": {
          "webp": "grubbets-conference-handouts-2022-06-03-sustainable-pet-food-01-card.webp",
          "w": 695,
          "h": 900,
          "kb": 62.7
        },
        "full": {
          "webp": "grubbets-conference-handouts-2022-06-03-sustainable-pet-food-01-full.webp",
          "w": 1275,
          "h": 1650,
          "kb": 136.0,
          "jpg": "grubbets-conference-handouts-2022-06-03-sustainable-pet-food-01-full.jpg",
          "jpgKb": 224.6
        }
      },
      "lqip": "grubbets-conference-handouts-2022-06-03-sustainable-pet-food-01-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABMDASIAAhEBAxEB/8QAGAABAQADAAAAAAAAAAAAAAAAAAUBAwT/xAAgEAACAgICAwEBAAAAAAAAAAAAAQMRAgQSIQUGFTFS/8QAFwEAAwEAAAAAAAAAAAAAAAAAAAIDAf/EABsRAAICAwEAAAAAAAAAAAAAAAABAhITFEFR/9oADAMBAAIRAxEAPwDo+PqqdRcm7Nr9ch/Vk0U1lrqTl1Y2tp8ajoXKl0SsSavWY2r5MFWLbSixWT7rsBlXptYkHLyeu8lTGflIHVMAlrwIWZj6kH9AANeAWZ//2Q==",
      "project": "grubbets",
      "title": "Sustainable Pet Food",
      "client": "Grubbets",
      "year": "2022",
      "medium": "Conference handout · 8.5×11 in",
      "featured": false,
      "blurb": "The companion sheet on black soldier fly larvae in pet nutrition, sharing a format so the pair could be laid out side by side on the same table.",
      "engagement": "Client project",
      "inhouse": false
    },
    {
      "slug": "revolve-branding-revolve-33x41-banner-lr",
      "source": "Revolve Branding/Revolve_33x41 Banner_LR.jpeg",
      "srcW": 4950,
      "srcH": 6150,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "revolve-branding-revolve-33x41-banner-lr-thumb.webp",
          "w": 386,
          "h": 480,
          "kb": 25.0
        },
        "card": {
          "webp": "revolve-branding-revolve-33x41-banner-lr-card.webp",
          "w": 724,
          "h": 900,
          "kb": 59.6
        },
        "full": {
          "webp": "revolve-branding-revolve-33x41-banner-lr-full.webp",
          "w": 1610,
          "h": 2000,
          "kb": 166.1,
          "jpg": "revolve-branding-revolve-33x41-banner-lr-full.jpg",
          "jpgKb": 330.2
        }
      },
      "lqip": "revolve-branding-revolve-33x41-banner-lr-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABMDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQDBQL/xAAhEAABBAIBBQEAAAAAAAAAAAABAAIDEQQSIRMUIkFRU//EABcBAAMBAAAAAAAAAAAAAAAAAAABAgP/xAAZEQEAAgMAAAAAAAAAAAAAAAAAAQIREhP/2gAMAwEAAhEDEQA/ANGv3iMgIv4vGLKZ5C0+NLnYpcHDa9VXkxbC8ayfdKeVWWsLHPDXEWOEXHMGVfLXIlxqNYXNxotaM4VOIYcdhHVBtEVnlp3Tf0aiIkMv/9k=",
      "project": "roplast",
      "title": "Scrap to PCR",
      "client": "Revolve Recycling",
      "year": "2019",
      "medium": "33×41 in banner · left/right",
      "featured": true,
      "blurb": "A process diagram that follows plastic scrap all the way around the loop and back to a post-consumer resin bag on a shelf, illustrated rather than explained.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "roplast-marketing-piece",
      "source": "Roplast Marketing Piece.jpg",
      "srcW": 5376,
      "srcH": 3024,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "roplast-marketing-piece-thumb.webp",
          "w": 480,
          "h": 270,
          "kb": 15.5
        },
        "card": {
          "webp": "roplast-marketing-piece-card.webp",
          "w": 900,
          "h": 506,
          "kb": 38.5
        },
        "full": {
          "webp": "roplast-marketing-piece-full.webp",
          "w": 2000,
          "h": 1125,
          "kb": 115.1,
          "jpg": "roplast-marketing-piece-full.jpg",
          "jpgKb": 209.8
        }
      },
      "lqip": "roplast-marketing-piece-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAIEAQP/xAAeEAACAgEFAQAAAAAAAAAAAAABAgAEAwUREiExE//EABcBAAMBAAAAAAAAAAAAAAAAAAIDBAX/xAAeEQACAgICAwAAAAAAAAAAAAABAgADBBIRISIxMv/aAAwDAQACEQMRAD8As1KxlWymNG4g+ztS3DMrZORj26gsHs7Ra1D4PzDkmZOPdQtYDjuNtRj8mXAEewmAk9GEiydDZynqHXsF8p//2Q==",
      "project": "roplast",
      "title": "Ridiculously Good Printing",
      "client": "Roplast",
      "year": "2016",
      "medium": "Trade-show booth graphics",
      "featured": true,
      "blurb": "An ASG trade-show booth built as a wall of framed art prints, with a typographic centrepiece and material samples you could reach out and touch.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "yeson67",
      "source": "YesOn67.jpg",
      "srcW": 2688,
      "srcH": 1512,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "yeson67-thumb.webp",
          "w": 480,
          "h": 270,
          "kb": 34.3
        },
        "card": {
          "webp": "yeson67-card.webp",
          "w": 900,
          "h": 506,
          "kb": 98.3
        },
        "full": {
          "webp": "yeson67-full.webp",
          "w": 2000,
          "h": 1125,
          "kb": 345.2,
          "jpg": "yeson67-full.jpg",
          "jpgKb": 508.2
        }
      },
      "lqip": "yeson67-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAB/8QAHhABAAEEAgMAAAAAAAAAAAAAAQACAwQREkETIXH/xAAWAQEBAQAAAAAAAAAAAAAAAAACAQP/xAAYEQADAQEAAAAAAAAAAAAAAAAAAREhQf/aAAwDAQACEQMRAD8AI5Fy5Uc3kPUVYotV73TpCAoeyKx8h2iSqBd4a5/hGjj6JQN1arj9lMoPT//Z",
      "project": "roplast",
      "title": "Yes on 67",
      "client": "Roplast",
      "year": "2018",
      "medium": "Yard sign · installed",
      "featured": false,
      "blurb": "A lawn sign for a California recycling ballot measure, designed to hold its own at a distance and photograph well in the news.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "global-shop-2016-1",
      "source": "Global Shop 2016_1.jpg",
      "srcW": 562,
      "srcH": 636,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "global-shop-2016-1-thumb.webp",
          "w": 424,
          "h": 480,
          "kb": 32.8
        },
        "card": {
          "webp": "global-shop-2016-1-card.webp",
          "w": 562,
          "h": 636,
          "kb": 55.8
        },
        "full": {
          "webp": "global-shop-2016-1-full.webp",
          "w": 562,
          "h": 636,
          "kb": 55.8,
          "jpg": "global-shop-2016-1-full.jpg",
          "jpgKb": 61.2
        }
      },
      "lqip": "global-shop-2016-1-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABUDASIAAhEBAxEB/8QAGQABAAIDAAAAAAAAAAAAAAAAAAQFAQMG/8QAIRAAAgMAAQMFAAAAAAAAAAAAAgMAAREEEiJRBTEyQZH/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQMC/8QAFxEBAQEBAAAAAAAAAAAAAAAAAAEREv/aAAwDAQACEQMRAD8AouOBLbpBLXkoBqaYQ6VVN4AunVo/swzbcQ+w+Ibp5YoHsEj7R6cidAXoamYVFmxGzqK5rDLqV8vElUBAsWM+4iSilSa5NZXdkREOqfMf/9k=",
      "project": "roplast",
      "title": "Global Shop 2016",
      "client": "Roplast",
      "year": "2016",
      "medium": "Event identity",
      "featured": false,
      "blurb": "Event collateral for Roplast's 2016 Global Shop gathering.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "global-shop-2016-2",
      "source": "Global Shop 2016_2.jpg",
      "srcW": 1152,
      "srcH": 864,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "global-shop-2016-2-thumb.webp",
          "w": 480,
          "h": 360,
          "kb": 28.5
        },
        "card": {
          "webp": "global-shop-2016-2-card.webp",
          "w": 900,
          "h": 675,
          "kb": 67.7
        },
        "full": {
          "webp": "global-shop-2016-2-full.webp",
          "w": 1152,
          "h": 864,
          "kb": 94.6,
          "jpg": "global-shop-2016-2-full.jpg",
          "jpgKb": 173.7
        }
      },
      "lqip": "global-shop-2016-2-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAASABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAQBBf/EACAQAAMAAQQCAwAAAAAAAAAAAAABAgMEERIxBRMhMkL/xAAXAQADAQAAAAAAAAAAAAAAAAAAAQID/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAERAv/aAAwDAQACEQMRAD8AnwObWy6KPbKlzt8nGjUPGk0+hl8rkq5pJLiLSrpWdQs5cc2+wIseprNVVXbA04Z6lIv0zQCxlGk+7AAEM//Z",
      "project": "roplast",
      "title": "Global Shop 2016 — Wide",
      "client": "Roplast",
      "year": "2016",
      "medium": "Event identity · banner",
      "featured": false,
      "blurb": "The wide-format companion to the Global Shop event collateral.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-cleancarry-2",
      "source": "Customer Bag Designs/CleanCarry-2.jpg",
      "srcW": 1000,
      "srcH": 1000,
      "orientation": "square",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-cleancarry-2-thumb.webp",
          "w": 480,
          "h": 480,
          "kb": 18.3
        },
        "card": {
          "webp": "customer-bag-designs-cleancarry-2-card.webp",
          "w": 900,
          "h": 900,
          "kb": 44.4
        },
        "full": {
          "webp": "customer-bag-designs-cleancarry-2-full.webp",
          "w": 1000,
          "h": 1000,
          "kb": 52.5,
          "jpg": "customer-bag-designs-cleancarry-2-full.jpg",
          "jpgKb": 105.6
        }
      },
      "lqip": "customer-bag-designs-cleancarry-2-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAUDBAb/xAAhEAACAgEEAgMAAAAAAAAAAAAAAQIDBAUREyESUSIjQf/EABYBAQEBAAAAAAAAAAAAAAAAAAEAAv/EABkRAQACAwAAAAAAAAAAAAAAAAABEQIxQf/aAAwDAQACEQMRAD8A9k3scf2cykvZtkT44uRPepR99oqMZUrJ7gxxLeavyBBlqFE7qmq32RI6Xkt/JfoBqNDq7gUSopUZPsAGS//Z",
      "project": "bags",
      "title": "CleanCarry",
      "client": "Undisclosed",
      "year": "2020",
      "medium": "Packaging concept · tamper-evident",
      "featured": true,
      "blurb": "A tamper-evident bag concept that solves a real grocery problem — resealable after open — and prints the promise across the front in oversized type.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200401-grocery-0399-2",
      "source": "Customer Bag Designs/20200401-Grocery_0399-2.jpg",
      "srcW": 2016,
      "srcH": 1000,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200401-grocery-0399-2-thumb.webp",
          "w": 480,
          "h": 238,
          "kb": 21.1
        },
        "card": {
          "webp": "customer-bag-designs-20200401-grocery-0399-2-card.webp",
          "w": 900,
          "h": 446,
          "kb": 59.6
        },
        "full": {
          "webp": "customer-bag-designs-20200401-grocery-0399-2-full.webp",
          "w": 2000,
          "h": 992,
          "kb": 208.8,
          "jpg": "customer-bag-designs-20200401-grocery-0399-2-full.jpg",
          "jpgKb": 325.7
        }
      },
      "lqip": "customer-bag-designs-20200401-grocery-0399-2-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABgDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQBAwX/xAAfEAACAgEEAwAAAAAAAAAAAAABAgADBAURIjEVIUH/xAAWAQEBAQAAAAAAAAAAAAAAAAABAgP/xAAYEQEBAAMAAAAAAAAAAAAAAAAAEQECIf/aAAwDAQACEQMRAD8A2NRvtrDMG66inkMg4y8vZjmoIC5B6ir0oKF2H2DWZW4V2QLlUtxMJOEu96wija3r/9k=",
      "project": "bags",
      "title": "Grocery Bag — Pan Dulce",
      "client": "Undisclosed",
      "year": "2020",
      "medium": "Reusable bag · grocery",
      "featured": true,
      "blurb": "A panadería bag that uses a warm woodgrain print as the background and lets the food photography carry all the appetite appeal.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-cleancarry-specs-copy",
      "source": "Customer Bag Designs/CleanCarry_Specs-copy.jpg",
      "srcW": 552,
      "srcH": 438,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-cleancarry-specs-copy-thumb.webp",
          "w": 480,
          "h": 381,
          "kb": 16.7
        },
        "card": {
          "webp": "customer-bag-designs-cleancarry-specs-copy-card.webp",
          "w": 552,
          "h": 438,
          "kb": 20.8
        },
        "full": {
          "webp": "customer-bag-designs-cleancarry-specs-copy-full.webp",
          "w": 552,
          "h": 438,
          "kb": 20.8,
          "jpg": "customer-bag-designs-cleancarry-specs-copy-full.jpg",
          "jpgKb": 31.6
        }
      },
      "lqip": "customer-bag-designs-cleancarry-specs-copy-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAATABgDASIAAhEBAxEB/8QAGgABAAIDAQAAAAAAAAAAAAAAAAECAwQFBv/EAB4QAAICAgIDAAAAAAAAAAAAAAABAhEDIRJREyJB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEQMRAD8A9hKaiUWZ8qa0UzettbZqeTNLImougSuhHk5XegVhkdpNAIytJ/CFFdIAKml0AAP/2Q==",
      "project": "bags",
      "title": "CleanCarry Specification",
      "client": "Undisclosed",
      "year": "2020",
      "medium": "Spec sheet · production reference",
      "featured": false,
      "blurb": "The production specification sheet that accompanies the CleanCarry concept to the factory floor.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200401-industrial-0417-s",
      "source": "Customer Bag Designs/20200401-Industrial_0417-s.jpg",
      "srcW": 1728,
      "srcH": 1000,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200401-industrial-0417-s-thumb.webp",
          "w": 480,
          "h": 278,
          "kb": 26.1
        },
        "card": {
          "webp": "customer-bag-designs-20200401-industrial-0417-s-card.webp",
          "w": 900,
          "h": 521,
          "kb": 75.4
        },
        "full": {
          "webp": "customer-bag-designs-20200401-industrial-0417-s-full.webp",
          "w": 1728,
          "h": 1000,
          "kb": 223.5,
          "jpg": "customer-bag-designs-20200401-industrial-0417-s-full.jpg",
          "jpgKb": 330.9
        }
      },
      "lqip": "customer-bag-designs-20200401-industrial-0417-s-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIDBP/EACEQAAEEAAYDAAAAAAAAAAAAAAIAAQMEBRESEyExFCRB/8QAFgEBAQEAAAAAAAAAAAAAAAAAAwAC/8QAGREBAAMBAQAAAAAAAAAAAAAAAQACESED/9oADAMBAAIRAxEAPwDVjNmWW6MUT8stdO7YCmfkck3DJZanubmps1aOruRELl9RLZrpEwHIlC8W9pfp0K0OHDHKxMXSFnzbp2Vs3k//2Q==",
      "project": "bags",
      "title": "Industrial Tote",
      "client": "Undisclosed",
      "year": "2020",
      "medium": "Reusable bag · industrial",
      "featured": false,
      "blurb": "A heavy-duty tote developed alongside the grocery line, trading photography for a spec-forward layout that survives industrial use.",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-california-stock-bags",
      "source": "Customer Bag Designs/California-Stock-Bags.jpg",
      "srcW": 1896,
      "srcH": 1100,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-california-stock-bags-thumb.webp",
          "w": 480,
          "h": 278,
          "kb": 17.0
        },
        "card": {
          "webp": "customer-bag-designs-california-stock-bags-card.webp",
          "w": 900,
          "h": 522,
          "kb": 49.6
        },
        "full": {
          "webp": "customer-bag-designs-california-stock-bags-full.webp",
          "w": 1896,
          "h": 1100,
          "kb": 177.8,
          "jpg": "customer-bag-designs-california-stock-bags-full.jpg",
          "jpgKb": 248.5
        }
      },
      "lqip": "customer-bag-designs-california-stock-bags-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAwAEBv/EAB4QAAEFAAMBAQAAAAAAAAAAAAEAAgMEEQUSMRNB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgH/xAAYEQADAQEAAAAAAAAAAAAAAAAAAREhQf/aAAwDAQACEQMRAD8A6G/Zcx4DT4llt9KRlDSTiK9REr+4fhTOrbT+W/nqTgdpg4vkjNMWFpGqTUuNbDMH9tKlHOCP/9k=",
      "project": "bags",
      "title": "California Stock Bags",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200330grocery-0001",
      "source": "Customer Bag Designs/20200330Grocery_0001.jpg",
      "srcW": 803,
      "srcH": 963,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200330grocery-0001-thumb.webp",
          "w": 400,
          "h": 480,
          "kb": 28.0
        },
        "card": {
          "webp": "customer-bag-designs-20200330grocery-0001-card.webp",
          "w": 750,
          "h": 900,
          "kb": 75.0
        },
        "full": {
          "webp": "customer-bag-designs-20200330grocery-0001-full.webp",
          "w": 803,
          "h": 963,
          "kb": 83.6,
          "jpg": "customer-bag-designs-20200330grocery-0001-full.jpg",
          "jpgKb": 127.5
        }
      },
      "lqip": "customer-bag-designs-20200330grocery-0001-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABQDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAQFBgP/xAAiEAABBQABAwUAAAAAAAAAAAACAAEDBBEFEjFRExQiMkH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABcRAQEBAQAAAAAAAAAAAAAAAAABEUH/2gAMAwEAAhEDEQA/ANHyV+OCIwYvnnZUtezCNiI+vHL7Ljzcj+/IWfuoMQgG+oi3C3UUwSRsQFreUVTxRs9EM3NRIVXIVJJr8hkL5+OoI05zl6SZ2byiKemNFx0JRVBDdx0RFQf/2Q==",
      "project": "bags",
      "title": "Grocery 0001",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0252",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0252.jpg",
      "srcW": 960,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0252-thumb.webp",
          "w": 461,
          "h": 480,
          "kb": 25.5
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0252-card.webp",
          "w": 864,
          "h": 900,
          "kb": 77.6
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0252-full.webp",
          "w": 960,
          "h": 1000,
          "kb": 93.5,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0252-full.jpg",
          "jpgKb": 129.4
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0252-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABcDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAUDBgH/xAAfEAACAgICAwEAAAAAAAAAAAABAgAEAxEhMQUSURP/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABcRAQEBAQAAAAAAAAAAAAAAAAEAAhH/2gAMAwEAAhEDEQA/AOtsZ1xIdnmTqlxlsMr8qT3PfKtrIsnhyG19gd8eVDHS6UEMNiJhS3+C7iMptjfptZA9TqTmo5sbaA38iIUJmms1UZMChu4iIoX/2Q==",
      "project": "bags",
      "title": "Grocery 0252",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0255",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0255.jpg",
      "srcW": 922,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0255-thumb.webp",
          "w": 443,
          "h": 480,
          "kb": 29.6
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0255-card.webp",
          "w": 830,
          "h": 900,
          "kb": 82.6
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0255-full.webp",
          "w": 922,
          "h": 1000,
          "kb": 99.0,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0255-full.jpg",
          "jpgKb": 139.0
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0255-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABYDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAUGBP/EACAQAAICAQUAAwAAAAAAAAAAAAECAAMRBAUSITEUQWH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/EABgRAQEBAQEAAAAAAAAAAAAAAAEAEQJB/9oADAMBAAIRAxEAPwDXX3LRWXY4wJAO5H5Kvy9Pn5O7eKy4GT1iRAiNW7VjJH3ENa8tdXYtiBlOciJH2BrGobmxMR65xyB0qOt0xvXoyLbt99XIVr0YiXMJVNq0r6egiz0xEQXWQv/Z",
      "project": "bags",
      "title": "Grocery 0255",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0269",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0269.jpg",
      "srcW": 958,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0269-thumb.webp",
          "w": 460,
          "h": 480,
          "kb": 23.6
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0269-card.webp",
          "w": 862,
          "h": 900,
          "kb": 72.3
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0269-full.webp",
          "w": 958,
          "h": 1000,
          "kb": 87.3,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0269-full.jpg",
          "jpgKb": 120.5
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0269-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABcDASIAAhEBAxEB/8QAGQABAAIDAAAAAAAAAAAAAAAAAAQFAQMG/8QAHhAAAgIBBQEAAAAAAAAAAAAAAAECAxEEEhQhMQX/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwDr7bY1QcpMqufYtWsPMH6iZ9FboKOPSAtta87JVXcZKUU0DTpW3XlgqM6ml2wwnhkLhyg+1lsACwqjsgkAAP/Z",
      "project": "bags",
      "title": "Grocery 0269",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0274",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0274.jpg",
      "srcW": 858,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0274-thumb.webp",
          "w": 412,
          "h": 480,
          "kb": 30.0
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0274-card.webp",
          "w": 772,
          "h": 900,
          "kb": 92.0
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0274-full.webp",
          "w": 858,
          "h": 1000,
          "kb": 110.2,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0274-full.jpg",
          "jpgKb": 141.2
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0274-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABUDASIAAhEBAxEB/8QAGQABAQADAQAAAAAAAAAAAAAAAAMCBAYF/8QAIhAAAgICAQMFAAAAAAAAAAAAAQIAAwQRBRMUISIxQVFx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwL/xAAaEQADAQADAAAAAAAAAAAAAAAAARECAxIh/9oADAMBAAIRAxEAPwDqczKWlCAfWfYTRxM10ZuqdjchzKv3lZTcjkgqgP3C1tpxD54lqenRV2LYgZTsGJDjxrET8iKC1HDHLxmscMPMhbx7XMNnQERI6K0tbaR6FVYqrCD4iIlhn//Z",
      "project": "bags",
      "title": "Grocery 0274",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0279",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0279.jpg",
      "srcW": 755,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0279-thumb.webp",
          "w": 362,
          "h": 480,
          "kb": 13.4
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0279-card.webp",
          "w": 680,
          "h": 900,
          "kb": 38.5
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0279-full.webp",
          "w": 755,
          "h": 1000,
          "kb": 46.0,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0279-full.jpg",
          "jpgKb": 76.2
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0279-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABIDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQCBQb/xAAgEAABBAEEAwAAAAAAAAAAAAAAAQIDBBESITFBE1Fh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/APSXbKo1WR8mqEz1bol5TsiuztilVMblNV6O0r7KyC7HRABJR2qLJ9+zVet4sfAB2jFQAAv/2Q==",
      "project": "bags",
      "title": "Grocery 0279",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0307",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0307.jpg",
      "srcW": 928,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0307-thumb.webp",
          "w": 445,
          "h": 480,
          "kb": 17.4
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0307-card.webp",
          "w": 835,
          "h": 900,
          "kb": 53.4
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0307-full.webp",
          "w": 928,
          "h": 1000,
          "kb": 64.5,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0307-full.jpg",
          "jpgKb": 98.7
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0307-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABYDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAMFBgT/xAAiEAACAgICAQUBAAAAAAAAAAABAwACBBEFEiETIiMxQVH/xAAWAQEBAQAAAAAAAAAAAAAAAAABAAL/xAAXEQEBAQEAAAAAAAAAAAAAAAAAESFB/9oADAMBAAIRAxEAPwDYNYFLNj+CU6MljcqzDfQH0J0c06ykeyuyZS43I9GnvXQ1GZU1dLdqgxIcJnq49bf2IJByqmNT8Y2ZQK4rIc3yNDfkxE1cHWnxElCKrJ2QIiJkv//Z",
      "project": "bags",
      "title": "Grocery 0307",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20200331-grocery-pp-0332",
      "source": "Customer Bag Designs/20200331-Grocery-PP_0332.jpg",
      "srcW": 799,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0332-thumb.webp",
          "w": 384,
          "h": 480,
          "kb": 24.8
        },
        "card": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0332-card.webp",
          "w": 719,
          "h": 900,
          "kb": 71.7
        },
        "full": {
          "webp": "customer-bag-designs-20200331-grocery-pp-0332-full.webp",
          "w": 799,
          "h": 1000,
          "kb": 85.5,
          "jpg": "customer-bag-designs-20200331-grocery-pp-0332-full.jpg",
          "jpgKb": 124.5
        }
      },
      "lqip": "customer-bag-designs-20200331-grocery-pp-0332-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABMDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAYEAgf/xAAiEAABBAIBBAMAAAAAAAAAAAABAAIDBBESBRMUIUFRYXL/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAh/9oADAMBAAIRAxEAPwCpt2mRROw4bYU9U5p8dzR/kE4WHlbEjLbwCcZWJp3ma77U0ehsfswO+QizVCe2j/KKhLcvVn70jTIJ8LunwlqRzSRqM+0RBWQxdOJrT6GEREH/2Q==",
      "project": "bags",
      "title": "Grocery 0332",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20080518-grocery-0439",
      "source": "Customer Bag Designs/20080518-grocery_0439.jpg",
      "srcW": 786,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20080518-grocery-0439-thumb.webp",
          "w": 377,
          "h": 480,
          "kb": 21.6
        },
        "card": {
          "webp": "customer-bag-designs-20080518-grocery-0439-card.webp",
          "w": 707,
          "h": 900,
          "kb": 57.5
        },
        "full": {
          "webp": "customer-bag-designs-20080518-grocery-0439-full.webp",
          "w": 786,
          "h": 1000,
          "kb": 68.5,
          "jpg": "customer-bag-designs-20080518-grocery-0439-full.jpg",
          "jpgKb": 103.7
        }
      },
      "lqip": "customer-bag-designs-20080518-grocery-0439-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABMDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAUDBAL/xAAhEAACAgICAQUAAAAAAAAAAAAAAQIDBBESE3EFITEyUf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAGREAAwEBAQAAAAAAAAAAAAAAAAERAhIh/9oADAMBAAIRAxEAPwC9fm2rJ6oxfk2xuyNrc57X4estxg9rSkcVFsnNtv5J8pO0XXkLO0DOH0XgFAkz1am6didS2jjqqyE0uLAJawm6Gl6rkq47XvoAFBH/2Q==",
      "project": "bags",
      "title": "Grocery 0439",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20080518-grocery-0444",
      "source": "Customer Bag Designs/20080518-grocery_0444.jpg",
      "srcW": 923,
      "srcH": 1000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20080518-grocery-0444-thumb.webp",
          "w": 443,
          "h": 480,
          "kb": 19.9
        },
        "card": {
          "webp": "customer-bag-designs-20080518-grocery-0444-card.webp",
          "w": 831,
          "h": 900,
          "kb": 50.1
        },
        "full": {
          "webp": "customer-bag-designs-20080518-grocery-0444-full.webp",
          "w": 923,
          "h": 1000,
          "kb": 58.5,
          "jpg": "customer-bag-designs-20080518-grocery-0444-full.jpg",
          "jpgKb": 96.7
        }
      },
      "lqip": "customer-bag-designs-20080518-grocery-0444-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABYDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAMEBQb/xAAgEAABBAEEAwAAAAAAAAAAAAAAAQIDEQQFEjFBEyEz/8QAFwEAAwEAAAAAAAAAAAAAAAAAAQIDAP/EABkRAQEBAQEBAAAAAAAAAAAAAAEAEQIDEv/aAAwDAQACEQMRAD8A9iruiauVPdksmTa+kciEXPtPoD6I5b2O3JYJ4y3HzYMOwsGp4875UfF0YvDlKlbaUAn158rrOXX0+OSOGpOQAUADCVv/2Q==",
      "project": "bags",
      "title": "Grocery 0444",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "customer-bag-designs-20080518-grocery-0446",
      "source": "Customer Bag Designs/20080518-grocery_0446.jpg",
      "srcW": 1000,
      "srcH": 971,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "customer-bag-designs-20080518-grocery-0446-thumb.webp",
          "w": 480,
          "h": 466,
          "kb": 23.7
        },
        "card": {
          "webp": "customer-bag-designs-20080518-grocery-0446-card.webp",
          "w": 900,
          "h": 874,
          "kb": 59.4
        },
        "full": {
          "webp": "customer-bag-designs-20080518-grocery-0446-full.webp",
          "w": 1000,
          "h": 971,
          "kb": 70.7,
          "jpg": "customer-bag-designs-20080518-grocery-0446-full.jpg",
          "jpgKb": 117.7
        }
      },
      "lqip": "customer-bag-designs-20080518-grocery-0446-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAXABgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQFAgP/xAAfEAACAgIDAAMAAAAAAAAAAAABAgADERIEBTEhUaH/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAYEQEBAQEBAAAAAAAAAAAAAAABABECIf/aAAwDAQACEQMRAD8A3ezF5dWDaoDPWjk7KB+zrs13r1zjMzK80JoSSfuTM9tnIm21Q5ZyM5iSdQzOHLnPzEFOjHKjnUG1QQfJAeOxMRDTazruMaNjn2IiCLr7f//Z",
      "project": "bags",
      "title": "Grocery 0446",
      "client": "Undisclosed",
      "year": "Undated",
      "medium": "Print design",
      "featured": false,
      "blurb": "",
      "engagement": "In-house role",
      "inhouse": true
    },
    {
      "slug": "early-work-halloween-hires",
      "source": "Early Work/Halloween_HiRes.jpg",
      "srcW": 4500,
      "srcH": 6000,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "early-work-halloween-hires-thumb.webp",
          "w": 360,
          "h": 480,
          "kb": 46.5
        },
        "card": {
          "webp": "early-work-halloween-hires-card.webp",
          "w": 675,
          "h": 900,
          "kb": 118.0
        },
        "full": {
          "webp": "early-work-halloween-hires-full.webp",
          "w": 1500,
          "h": 2000,
          "kb": 366.5,
          "jpg": "early-work-halloween-hires-full.jpg",
          "jpgKb": 573.3
        }
      },
      "lqip": "early-work-halloween-hires-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABIDASIAAhEBAxEB/8QAGQABAAMBAQAAAAAAAAAAAAAAAAIDBQEE/8QAHhAAAgICAgMAAAAAAAAAAAAAAAECAxESBEIUIVL/xAAXAQADAQAAAAAAAAAAAAAAAAABAwQC/8QAHhEAAQMEAwAAAAAAAAAAAAAAAAECEQMSExQhIjH/2gAMAwEAAhEDEQA/AMTiuqXUuvjUov0R4VcNNmsltqThJtA6ybvdBm7V/IONLLA6xBV6nsrovqWHEm1dKONQCDM5eYLMDfCnwOQ+gADt1A6zD//Z",
      "project": "early",
      "title": "Halloween",
      "client": "Personal",
      "year": "Early",
      "medium": "Poster · 27 megapixel master",
      "featured": true,
      "blurb": "A seasonal poster produced at 27 megapixels, and a good lesson in how much resolution a wall-sized print actually needs.",
      "engagement": "Personal / student work",
      "inhouse": false
    },
    {
      "slug": "early-work-ferrari-shoe-ad",
      "source": "Early Work/Ferrari Shoe Ad.jpg",
      "srcW": 1024,
      "srcH": 768,
      "orientation": "landscape",
      "variants": {
        "thumb": {
          "webp": "early-work-ferrari-shoe-ad-thumb.webp",
          "w": 480,
          "h": 360,
          "kb": 15.0
        },
        "card": {
          "webp": "early-work-ferrari-shoe-ad-card.webp",
          "w": 900,
          "h": 675,
          "kb": 34.5
        },
        "full": {
          "webp": "early-work-ferrari-shoe-ad-full.webp",
          "w": 1024,
          "h": 768,
          "kb": 39.8,
          "jpg": "early-work-ferrari-shoe-ad-full.jpg",
          "jpgKb": 77.6
        }
      },
      "lqip": "early-work-ferrari-shoe-ad-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAASABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAIDBv/EABsQAAIDAQEBAAAAAAAAAAAAAAABAhExAxIh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAWEQEBAQAAAAAAAAAAAAAAAAAAAUH/2gAMAwEAAhEDEQA/AORi/Er1Gq6esgQqT+qy10V5QWSazncpZQKk7dgIiRIAWLiAAj//2Q==",
      "project": "early",
      "title": "Ferrari Shoe Ad",
      "client": "Personal",
      "year": "Early",
      "medium": "Ad layout",
      "featured": false,
      "blurb": "An early advertising layout study built around a single product crop.",
      "engagement": "Personal / student work",
      "inhouse": false
    },
    {
      "slug": "early-work-kiwanis-wine",
      "source": "Early Work/Kiwanis Wine.jpg",
      "srcW": 582,
      "srcH": 900,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "early-work-kiwanis-wine-thumb.webp",
          "w": 310,
          "h": 480,
          "kb": 37.0
        },
        "card": {
          "webp": "early-work-kiwanis-wine-card.webp",
          "w": 582,
          "h": 900,
          "kb": 87.3
        },
        "full": {
          "webp": "early-work-kiwanis-wine-full.webp",
          "w": 582,
          "h": 900,
          "kb": 87.3,
          "jpg": "early-work-kiwanis-wine-full.jpg",
          "jpgKb": 127.2
        }
      },
      "lqip": "early-work-kiwanis-wine-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABADASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAIBAwT/xAAeEAACAgIDAQEAAAAAAAAAAAABAgAEAxESISJRE//EABYBAQEBAAAAAAAAAAAAAAAAAAEDBP/EABcRAQADAAAAAAAAAAAAAAAAAAABERL/2gAMAwEAAhEDEQA/AMderiGAORyaLaqYvxLoNN8lNTJpdMT3JtElPJIi01OiIOKAhhuLk9ISW7+QhFR//9k=",
      "project": "early",
      "title": "Kiwanis Wine",
      "client": "Kiwanis",
      "year": "Early",
      "medium": "Label / promotional",
      "featured": false,
      "blurb": "A wine label for a community organisation, with the small type set carefully enough to actually survive a bottle.",
      "engagement": "Personal / student work",
      "inhouse": false
    },
    {
      "slug": "early-work-ophir-elementary-t-shirts",
      "source": "Early Work/Ophir Elementary T-shirts.jpg",
      "srcW": 863,
      "srcH": 1012,
      "orientation": "portrait",
      "variants": {
        "thumb": {
          "webp": "early-work-ophir-elementary-t-shirts-thumb.webp",
          "w": 409,
          "h": 480,
          "kb": 27.9
        },
        "card": {
          "webp": "early-work-ophir-elementary-t-shirts-card.webp",
          "w": 767,
          "h": 900,
          "kb": 60.3
        },
        "full": {
          "webp": "early-work-ophir-elementary-t-shirts-full.webp",
          "w": 863,
          "h": 1012,
          "kb": 67.3,
          "jpg": "early-work-ophir-elementary-t-shirts-full.jpg",
          "jpgKb": 98.2
        }
      },
      "lqip": "early-work-ophir-elementary-t-shirts-lqip.jpg",
      "lqipData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABQDASIAAhEBAxEB/8QAGQABAAMBAQAAAAAAAAAAAAAAAAMFBgIE/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIAAwQRBTESEyEiUf/EABYBAQEBAAAAAAAAAAAAAAAAAAIBA//EABgRAQEBAQEAAAAAAAAAAAAAAAABIQKB/9oADAMBAAIRAxEAPwDNYeLXcjM7a1JRh0776kfG4j5doRG1uWVvCXVozew/WE/FJd4rYQB8CJzbWVsIJiVHr4nLGLlK7dCXeVz1L1Oq9sIiSzS5uMu7eTk/piIiZv/Z",
      "project": "early",
      "title": "Ophir Elementary T-Shirts",
      "client": "Ophir Elementary",
      "year": "Early",
      "medium": "Apparel · screen print",
      "featured": false,
      "blurb": "School apparel art, simplified to survive a single-colour screen print.",
      "engagement": "Personal / student work",
      "inhouse": false
    }
  ]
};
